// <auto-generated />
using CoreApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreApi.Migrations
{
    [DbContext(typeof(MathBrainRankingContext))]
    [Migration("20230303173429_IdErrorFix")]
    partial class IdErrorFix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoreApi.Models.EmProcesso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Processando")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("EmProcesso");
                });

            modelBuilder.Entity("CoreApi.Models.UserRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("IdUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("MelhorRanking")
                        .HasColumnType("float");

                    b.Property<float>("MelhorTempo")
                        .HasColumnType("real");

                    b.Property<int>("QtdAcertos")
                        .HasColumnType("int");

                    b.Property<double>("UltimoRanking")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("UserRanking");
                });
#pragma warning restore 612, 618
        }
    }
}
